apiVersion : apps/v1
kind: Deployment
metadata:
  name: flaskdemocluster
  labels: 
    app: flaskdemocluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskdemocluster
  template:
    metadata:
      labels:
        app: flaskdemocluster
    spec:
      containers:
        - name: "flaskdemoclustercont"
          image: "seunnuga93/pipelines-flask-docker"
          ports:
          - containerPort: 80
